import { PrismaClient, EventCategory, Theater, Side, Victor } from '@prisma/client';

const prisma = new PrismaClient();

const d = (s: string) => new Date(s);

async function main() {
  // Reset (order matters due to FKs)
  await prisma.battleParticipant.deleteMany();
  await prisma.campaignBattle.deleteMany();
  await prisma.battle.deleteMany();
  await prisma.campaign.deleteMany();
  await prisma.person.deleteMany();
  await prisma.event.deleteMany();

  // ─────────────────────────── PEOPLE ───────────────────────────
  const peopleData = [
    {
      key: 'eisenhower',
      fullName: 'Dwight D. Eisenhower',
      birthDate: d('1890-10-14'), deathDate: d('1969-03-28'),
      birthPlace: 'Denison, Texas, EE.UU.', nationality: 'Estadounidense',
      role: 'General', side: Side.ALLIED, rank: 'General del Ejército',
      biography: 'Comandante Supremo de las Fuerzas Expedicionarias Aliadas en Europa. Dirigió la Operación Overlord (desembarco de Normandía) y la campaña final contra la Alemania nazi. Posteriormente fue el 34.º presidente de Estados Unidos.',
      notablePositions: ['Comandante Supremo Aliado en Europa', 'Presidente de EE.UU. (1953-1961)'],
      keyAchievements: ['Planificación y ejecución del Día D', 'Liberación de Europa Occidental'],
    },
    {
      key: 'montgomery',
      fullName: 'Bernard Montgomery',
      birthDate: d('1887-11-17'), deathDate: d('1976-03-24'),
      birthPlace: 'Londres, Reino Unido', nationality: 'Británico',
      role: 'General', side: Side.ALLIED, rank: 'Mariscal de Campo',
      biography: 'Comandante del Octavo Ejército británico que derrotó a Rommel en El Alamein, punto de inflexión en el norte de África. Comandó las fuerzas terrestres aliadas en Normandía y lideró la fallida Operación Market Garden.',
      notablePositions: ['Comandante del 8.º Ejército', 'Comandante del 21.º Grupo de Ejércitos'],
      keyAchievements: ['Victoria en El Alamein', 'Mando terrestre en el Día D'],
    },
    {
      key: 'patton',
      fullName: 'George S. Patton',
      birthDate: d('1885-11-11'), deathDate: d('1945-12-21'),
      birthPlace: 'San Gabriel, California, EE.UU.', nationality: 'Estadounidense',
      role: 'General', side: Side.ALLIED, rank: 'General',
      biography: 'Uno de los comandantes blindados más agresivos y efectivos de los Aliados. Destacó en Sicilia y lideró el Tercer Ejército en su fulgurante avance por Francia y en el rescate de Bastogne durante la batalla de las Ardenas.',
      notablePositions: ['Comandante del 3.er Ejército de EE.UU.', 'Comandante del 7.º Ejército en Sicilia'],
      keyAchievements: ['Avance relámpago por Francia (1944)', 'Contraataque en las Ardenas'],
    },
    {
      key: 'zhukov',
      fullName: 'Gueorgui Zhúkov',
      birthDate: d('1896-12-01'), deathDate: d('1974-06-18'),
      birthPlace: 'Strelkovka, Rusia', nationality: 'Soviético',
      role: 'General', side: Side.ALLIED, rank: 'Mariscal de la Unión Soviética',
      biography: 'El comandante soviético más importante de la guerra. Organizó la defensa de Moscú y Leningrado, planificó la contraofensiva de Stalingrado, venció en Kursk y dirigió el asalto final sobre Berlín.',
      notablePositions: ['Jefe del Estado Mayor del Ejército Rojo', 'Comandante del 1.er Frente Bielorruso'],
      keyAchievements: ['Defensa de Moscú', 'Operación Urano en Stalingrado', 'Toma de Berlín'],
    },
    {
      key: 'rommel',
      fullName: 'Erwin Rommel',
      birthDate: d('1891-11-15'), deathDate: d('1944-10-14'),
      birthPlace: 'Heidenheim, Alemania', nationality: 'Alemán',
      role: 'General', side: Side.AXIS, rank: 'Mariscal de Campo',
      biography: 'Apodado "el Zorro del Desierto" por su brillante guerra de maniobras al mando del Afrika Korps. Posteriormente organizó las defensas del Muro Atlántico. Implicado en el complot del 20 de julio contra Hitler, fue forzado a suicidarse.',
      notablePositions: ['Comandante del Afrika Korps', 'Comandante del Grupo de Ejércitos B'],
      keyAchievements: ['Campañas del norte de África', 'Defensa de Normandía'],
    },
    {
      key: 'manstein',
      fullName: 'Erich von Manstein',
      birthDate: d('1887-11-24'), deathDate: d('1973-06-09'),
      birthPlace: 'Berlín, Alemania', nationality: 'Alemán',
      role: 'General', side: Side.AXIS, rank: 'Mariscal de Campo',
      biography: 'Considerado el estratega más capaz de la Wehrmacht. Ideó el plan de la hoz que derrotó a Francia en 1940 y ejecutó el "milagro" de la contraofensiva de Járkov tras Stalingrado.',
      notablePositions: ['Comandante del Grupo de Ejércitos Sur'],
      keyAchievements: ['Plan de la campaña de Francia', 'Tercera batalla de Járkov'],
    },
    {
      key: 'yamamoto',
      fullName: 'Isoroku Yamamoto',
      birthDate: d('1884-04-04'), deathDate: d('1943-04-18'),
      birthPlace: 'Nagaoka, Japón', nationality: 'Japonés',
      role: 'Almirante', side: Side.AXIS, rank: 'Almirante de Flota',
      biography: 'Comandante en jefe de la Flota Combinada japonesa. Planificó el ataque a Pearl Harbor pese a sus reservas sobre una guerra con EE.UU. Murió cuando su avión fue derribado por cazas estadounidenses en la Operación Vengeance.',
      notablePositions: ['Comandante de la Flota Combinada'],
      keyAchievements: ['Ataque a Pearl Harbor', 'Modernización de la aviación naval japonesa'],
    },
    {
      key: 'nimitz',
      fullName: 'Chester W. Nimitz',
      birthDate: d('1885-02-24'), deathDate: d('1966-02-20'),
      birthPlace: 'Fredericksburg, Texas, EE.UU.', nationality: 'Estadounidense',
      role: 'Almirante', side: Side.ALLIED, rank: 'Almirante de Flota',
      biography: 'Comandante en jefe de la Flota del Pacífico de EE.UU. Su victoria en Midway cambió el curso de la guerra del Pacífico, y dirigió la estrategia de "saltos de isla" hasta la rendición japonesa.',
      notablePositions: ['Comandante de la Flota del Pacífico'],
      keyAchievements: ['Victoria en Midway', 'Campaña de saltos de isla'],
    },
    {
      key: 'macarthur',
      fullName: 'Douglas MacArthur',
      birthDate: d('1880-01-26'), deathDate: d('1964-04-05'),
      birthPlace: 'Little Rock, Arkansas, EE.UU.', nationality: 'Estadounidense',
      role: 'General', side: Side.ALLIED, rank: 'General del Ejército',
      biography: 'Comandante Supremo Aliado en el Pacífico Suroccidental. Cumplió su promesa de regresar a Filipinas con el desembarco de Leyte y aceptó la rendición formal de Japón a bordo del USS Missouri.',
      notablePositions: ['Comandante Supremo del Pacífico Suroccidental', 'Comandante Supremo de la ocupación de Japón'],
      keyAchievements: ['Liberación de Filipinas', 'Reconstrucción del Japón de posguerra'],
    },
    {
      key: 'churchill',
      fullName: 'Winston Churchill',
      birthDate: d('1874-11-30'), deathDate: d('1965-01-24'),
      birthPlace: 'Woodstock, Reino Unido', nationality: 'Británico',
      role: 'Líder Político', side: Side.ALLIED,
      biography: 'Primer ministro británico durante la mayor parte de la guerra. Su liderazgo y oratoria sostuvieron la resistencia británica cuando el Reino Unido quedó solo frente a la Alemania nazi en 1940-41.',
      notablePositions: ['Primer Ministro del Reino Unido (1940-1945)'],
      keyAchievements: ['Liderazgo durante la Batalla de Inglaterra', 'Forja de la Gran Alianza'],
    },
    {
      key: 'roosevelt',
      fullName: 'Franklin D. Roosevelt',
      birthDate: d('1882-01-30'), deathDate: d('1945-04-12'),
      birthPlace: 'Hyde Park, Nueva York, EE.UU.', nationality: 'Estadounidense',
      role: 'Líder Político', side: Side.ALLIED,
      biography: 'Presidente de EE.UU. desde 1933 hasta su muerte en abril de 1945. Convirtió a su país en el "arsenal de la democracia" mediante la Ley de Préstamo y Arriendo y dirigió el esfuerzo bélico estadounidense en dos frentes.',
      notablePositions: ['Presidente de EE.UU. (1933-1945)'],
      keyAchievements: ['Ley de Préstamo y Arriendo', 'Conferencias aliadas de Casablanca, Teherán y Yalta'],
    },
    {
      key: 'stalin',
      fullName: 'Iósif Stalin',
      birthDate: d('1878-12-18'), deathDate: d('1953-03-05'),
      birthPlace: 'Gori, Georgia', nationality: 'Soviético',
      role: 'Líder Político', side: Side.ALLIED,
      biography: 'Dictador de la Unión Soviética. Tras el pacto de no agresión con Alemania y la invasión sorpresa de 1941, dirigió el gigantesco esfuerzo bélico soviético que soportó el mayor peso de la guerra terrestre contra el Tercer Reich.',
      notablePositions: ['Secretario General del PCUS', 'Comandante Supremo del Ejército Rojo'],
      keyAchievements: ['Movilización industrial soviética', 'Victoria en el Frente Oriental'],
    },
    {
      key: 'hitler',
      fullName: 'Adolf Hitler',
      birthDate: d('1889-04-20'), deathDate: d('1945-04-30'),
      birthPlace: 'Braunau am Inn, Austria', nationality: 'Alemán',
      role: 'Líder Político', side: Side.AXIS,
      biography: 'Dictador de la Alemania nazi y responsable del estallido de la guerra en Europa y del Holocausto. Su interferencia creciente en las decisiones militares contribuyó a las derrotas alemanas. Se suicidó en su búnker de Berlín en abril de 1945.',
      notablePositions: ['Führer y Canciller del Reich'],
      keyAchievements: [],
    },
    {
      key: 'degaulle',
      fullName: 'Charles de Gaulle',
      birthDate: d('1890-11-22'), deathDate: d('1970-11-09'),
      birthPlace: 'Lille, Francia', nationality: 'Francés',
      role: 'Líder Político', side: Side.ALLIED, rank: 'General de Brigada',
      biography: 'Líder de la Francia Libre tras la caída de Francia en 1940. Desde Londres llamó a continuar la resistencia y reconstruyó un ejército francés que participó en la liberación de París y del país.',
      notablePositions: ['Líder de la Francia Libre', 'Presidente del Gobierno Provisional'],
      keyAchievements: ['Llamamiento del 18 de junio', 'Liberación de París'],
    },
    {
      key: 'guderian',
      fullName: 'Heinz Guderian',
      birthDate: d('1888-06-17'), deathDate: d('1954-05-14'),
      birthPlace: 'Kulm, Alemania', nationality: 'Alemán',
      role: 'General', side: Side.AXIS, rank: 'Coronel General',
      biography: 'Padre de la guerra relámpago (Blitzkrieg) y de las fuerzas panzer alemanas. Sus cuñas blindadas fueron decisivas en Polonia, Francia y la fase inicial de Barbarroja.',
      notablePositions: ['Comandante del 2.º Grupo Panzer', 'Inspector General de Tropas Blindadas'],
      keyAchievements: ['Doctrina Blitzkrieg', 'Cruce del Mosa en Sedán'],
    },
    {
      key: 'paulus',
      fullName: 'Friedrich Paulus',
      birthDate: d('1890-09-23'), deathDate: d('1957-02-01'),
      birthPlace: 'Guxhagen, Alemania', nationality: 'Alemán',
      role: 'General', side: Side.AXIS, rank: 'Mariscal de Campo',
      biography: 'Comandante del 6.º Ejército alemán en Stalingrado. Ascendido a mariscal por Hitler para inducirlo al suicidio antes que rendirse, se convirtió en el primer mariscal alemán capturado vivo al capitular en febrero de 1943.',
      notablePositions: ['Comandante del 6.º Ejército'],
      keyAchievements: [],
    },
    {
      key: 'chuikov',
      fullName: 'Vasili Chuikov',
      birthDate: d('1900-02-12'), deathDate: d('1982-03-18'),
      birthPlace: 'Serébrianye Prudý, Rusia', nationality: 'Soviético',
      role: 'General', side: Side.ALLIED, rank: 'General',
      biography: 'Comandante del 62.º Ejército soviético que defendió Stalingrado casa por casa con la táctica de "abrazar al enemigo". Sus tropas llegaron hasta Berlín, donde aceptó la rendición de la guarnición de la ciudad.',
      notablePositions: ['Comandante del 62.º Ejército'],
      keyAchievements: ['Defensa de Stalingrado', 'Asalto a Berlín'],
    },
    {
      key: 'doenitz',
      fullName: 'Karl Dönitz',
      birthDate: d('1891-09-16'), deathDate: d('1980-12-24'),
      birthPlace: 'Berlín, Alemania', nationality: 'Alemán',
      role: 'Almirante', side: Side.AXIS, rank: 'Gran Almirante',
      biography: 'Comandante de la flota de submarinos alemana y arquitecto de la guerra de manadas de lobos en el Atlántico. Sucedió a Hitler como jefe de Estado y autorizó la rendición incondicional de Alemania.',
      notablePositions: ['Comandante de la Kriegsmarine', 'Presidente del Reich (mayo 1945)'],
      keyAchievements: ['Campaña submarina del Atlántico'],
    },
  ];

  const people: Record<string, { id: string }> = {};
  for (const { key, ...data } of peopleData) {
    people[key] = await prisma.person.create({ data });
  }

  // ─────────────────────────── BATTLES ───────────────────────────
  const battlesData = [
    {
      key: 'poland',
      name: 'Invasión de Polonia',
      startDate: d('1939-09-01'), endDate: d('1939-10-06'),
      locationName: 'Polonia', latitude: 52.2297, longitude: 21.0122,
      theater: Theater.EUROPEAN, victor: Victor.AXIS,
      alliedCommander: 'Edward Rydz-Śmigły', axisCommander: 'Fedor von Bock / Gerd von Rundstedt',
      alliedStrength: 1000000, axisStrength: 1500000,
      alliedCasualties: 200000, axisCasualties: 45000, civilianCasualties: 150000,
      description: 'La invasión alemana de Polonia inauguró la Segunda Guerra Mundial en Europa y estrenó la guerra relámpago. La URSS invadió desde el este el 17 de septiembre conforme al pacto Ribbentrop-Mólotov.',
      strategicImportance: 'Desencadenó la declaración de guerra de Reino Unido y Francia a Alemania.',
      participants: [{ key: 'guderian', role: 'Comandante de cuerpo panzer' }],
    },
    {
      key: 'france',
      name: 'Batalla de Francia',
      startDate: d('1940-05-10'), endDate: d('1940-06-25'),
      locationName: 'Sedán, Francia', latitude: 49.7019, longitude: 4.9403,
      theater: Theater.EUROPEAN, victor: Victor.AXIS,
      alliedCommander: 'Maurice Gamelin / Maxime Weygand', axisCommander: 'Gerd von Rundstedt',
      alliedStrength: 3300000, axisStrength: 3350000,
      alliedCasualties: 2260000, axisCasualties: 163000, civilianCasualties: 90000,
      description: 'El plan de la hoz de Manstein atravesó las Ardenas y embolsó a los ejércitos aliados en Bélgica. Francia capituló en seis semanas, un desastre que nadie había previsto.',
      strategicImportance: 'Dejó al Reino Unido solo frente a Alemania y reconfiguró el equilibrio europeo.',
      participants: [
        { key: 'manstein', role: 'Autor del plan de campaña' },
        { key: 'guderian', role: 'Comandante del XIX Cuerpo Panzer' },
        { key: 'rommel', role: 'Comandante de la 7.ª División Panzer' },
      ],
    },
    {
      key: 'dunkirk',
      name: 'Evacuación de Dunkerque',
      startDate: d('1940-05-26'), endDate: d('1940-06-04'),
      locationName: 'Dunkerque, Francia', latitude: 51.0344, longitude: 2.3768,
      theater: Theater.EUROPEAN, victor: Victor.ALLIED,
      alliedCommander: 'Lord Gort / Bertram Ramsay', axisCommander: 'Gerd von Rundstedt',
      alliedStrength: 400000, axisStrength: 800000,
      alliedCasualties: 68000, axisCasualties: 20000, civilianCasualties: 1000,
      description: 'La Operación Dinamo evacuó a 338.000 soldados aliados atrapados en la bolsa de Dunkerque gracias a una flotilla improvisada de barcos militares y civiles.',
      strategicImportance: 'Salvó el núcleo del ejército británico, permitiendo continuar la guerra.',
      participants: [],
    },
    {
      key: 'britain',
      name: 'Batalla de Inglaterra',
      startDate: d('1940-07-10'), endDate: d('1940-10-31'),
      locationName: 'Sur de Inglaterra', latitude: 51.5074, longitude: -0.1278,
      theater: Theater.EUROPEAN, victor: Victor.ALLIED,
      alliedCommander: 'Hugh Dowding', axisCommander: 'Hermann Göring',
      alliedStrength: 1963, axisStrength: 2550,
      alliedCasualties: 1542, axisCasualties: 2585, civilianCasualties: 23000,
      description: 'Primera gran campaña librada enteramente en el aire. La RAF, apoyada por el radar, frustró el intento de la Luftwaffe de lograr la superioridad aérea previa a una invasión.',
      strategicImportance: 'Primera derrota estratégica de Hitler; canceló la invasión de Gran Bretaña.',
      participants: [{ key: 'churchill', role: 'Liderazgo político' }],
    },
    {
      key: 'moscow',
      name: 'Batalla de Moscú',
      startDate: d('1941-10-02'), endDate: d('1942-01-07'),
      locationName: 'Moscú, URSS', latitude: 55.7558, longitude: 37.6173,
      theater: Theater.EASTERN_FRONT, victor: Victor.ALLIED,
      alliedCommander: 'Gueorgui Zhúkov', axisCommander: 'Fedor von Bock',
      alliedStrength: 1250000, axisStrength: 1000000,
      alliedCasualties: 650000, axisCasualties: 400000, civilianCasualties: 40000,
      description: 'La Operación Tifón llevó a la Wehrmacht a las puertas de Moscú, pero el invierno, el agotamiento y la contraofensiva siberiana de Zhúkov la hicieron retroceder por primera vez.',
      strategicImportance: 'Primer gran fracaso terrestre alemán; acabó con el mito de la invencibilidad de la Blitzkrieg.',
      participants: [{ key: 'zhukov', role: 'Comandante de la defensa' }],
    },
    {
      key: 'leningrad',
      name: 'Sitio de Leningrado',
      startDate: d('1941-09-08'), endDate: d('1944-01-27'),
      locationName: 'Leningrado, URSS', latitude: 59.9343, longitude: 30.3351,
      theater: Theater.EASTERN_FRONT, victor: Victor.ALLIED,
      alliedCommander: 'Leonid Góvorov', axisCommander: 'Wilhelm Ritter von Leeb',
      alliedStrength: 930000, axisStrength: 725000,
      alliedCasualties: 1017000, axisCasualties: 580000, civilianCasualties: 1000000,
      description: 'Casi 900 días de asedio en los que la ciudad resistió el hambre, el frío y los bombardeos. Alrededor de un millón de civiles murieron, la mayoría de inanición.',
      strategicImportance: 'Inmovilizó a un grupo de ejércitos alemán completo durante casi tres años.',
      participants: [{ key: 'zhukov', role: 'Organizador inicial de la defensa' }],
    },
    {
      key: 'pearlharbor',
      name: 'Ataque a Pearl Harbor',
      startDate: d('1941-12-07'), endDate: d('1941-12-07'),
      locationName: 'Pearl Harbor, Hawái', latitude: 21.3649, longitude: -157.9507,
      theater: Theater.PACIFIC, victor: Victor.AXIS,
      alliedCommander: 'Husband E. Kimmel', axisCommander: 'Chūichi Nagumo',
      alliedStrength: 50000, axisStrength: 414,
      alliedCasualties: 3581, axisCasualties: 129, civilianCasualties: 68,
      description: 'Ataque sorpresa de la aviación naval japonesa contra la Flota del Pacífico de EE.UU. Hundió o dañó ocho acorazados, pero no encontró a los portaaviones estadounidenses.',
      strategicImportance: 'Provocó la entrada de Estados Unidos en la guerra.',
      participants: [{ key: 'yamamoto', role: 'Planificador del ataque' }],
    },
    {
      key: 'coralsea',
      name: 'Batalla del Mar del Coral',
      startDate: d('1942-05-04'), endDate: d('1942-05-08'),
      locationName: 'Mar del Coral', latitude: -15.0, longitude: 155.0,
      theater: Theater.PACIFIC, victor: Victor.INCONCLUSIVE,
      alliedCommander: 'Frank J. Fletcher', axisCommander: 'Shigeyoshi Inoue',
      alliedStrength: 27000, axisStrength: 28000,
      alliedCasualties: 656, axisCasualties: 966, civilianCasualties: 0,
      description: 'Primera batalla naval de la historia en la que las flotas nunca se avistaron: todo el combate lo libraron aviones embarcados. Detuvo la invasión japonesa de Port Moresby.',
      strategicImportance: 'Primer freno a la expansión japonesa; dejó dos portaaviones nipones fuera de Midway.',
      participants: [],
    },
    {
      key: 'midway',
      name: 'Batalla de Midway',
      startDate: d('1942-06-04'), endDate: d('1942-06-07'),
      locationName: 'Atolón de Midway', latitude: 28.2072, longitude: -177.3735,
      theater: Theater.PACIFIC, victor: Victor.ALLIED,
      alliedCommander: 'Chester W. Nimitz / Raymond Spruance', axisCommander: 'Isoroku Yamamoto / Chūichi Nagumo',
      alliedStrength: 26000, axisStrength: 40000,
      alliedCasualties: 307, axisCasualties: 3057, civilianCasualties: 0,
      description: 'Gracias al descifrado de los códigos navales japoneses, la US Navy tendió una emboscada que hundió cuatro portaaviones de la flota de Nagumo en un solo día.',
      strategicImportance: 'Punto de inflexión del Pacífico: Japón perdió la iniciativa estratégica para siempre.',
      participants: [
        { key: 'nimitz', role: 'Comandante en jefe' },
        { key: 'yamamoto', role: 'Comandante de la Flota Combinada' },
      ],
    },
    {
      key: 'guadalcanal',
      name: 'Campaña de Guadalcanal',
      startDate: d('1942-08-07'), endDate: d('1943-02-09'),
      locationName: 'Guadalcanal, Islas Salomón', latitude: -9.4333, longitude: 160.05,
      theater: Theater.PACIFIC, victor: Victor.ALLIED,
      alliedCommander: 'Alexander Vandegrift / William Halsey', axisCommander: 'Harukichi Hyakutake',
      alliedStrength: 60000, axisStrength: 36000,
      alliedCasualties: 7100, axisCasualties: 31000, civilianCasualties: 0,
      description: 'Primera gran ofensiva terrestre aliada en el Pacífico. Seis meses de brutales combates terrestres, navales y aéreos por el control del aeródromo Henderson.',
      strategicImportance: 'Inició la ofensiva aliada en el Pacífico y desangró a la aviación naval japonesa.',
      participants: [],
    },
    {
      key: 'elalamein',
      name: 'Segunda Batalla de El Alamein',
      startDate: d('1942-10-23'), endDate: d('1942-11-11'),
      locationName: 'El Alamein, Egipto', latitude: 30.8333, longitude: 28.95,
      theater: Theater.NORTH_AFRICAN, victor: Victor.ALLIED,
      alliedCommander: 'Bernard Montgomery', axisCommander: 'Erwin Rommel',
      alliedStrength: 195000, axisStrength: 116000,
      alliedCasualties: 13560, axisCasualties: 37000, civilianCasualties: 0,
      description: 'El Octavo Ejército de Montgomery rompió las líneas del Eje tras doce días de combate de desgaste, forzando la larga retirada del Afrika Korps hacia Túnez.',
      strategicImportance: 'Salvó el canal de Suez. "Antes de Alamein nunca tuvimos una victoria; después, nunca una derrota" (Churchill).',
      participants: [
        { key: 'montgomery', role: 'Comandante del 8.º Ejército' },
        { key: 'rommel', role: 'Comandante del Panzerarmee Afrika' },
      ],
    },
    {
      key: 'stalingrad',
      name: 'Batalla de Stalingrado',
      startDate: d('1942-08-23'), endDate: d('1943-02-02'),
      locationName: 'Stalingrado, URSS', latitude: 48.708, longitude: 44.5133,
      theater: Theater.EASTERN_FRONT, victor: Victor.ALLIED,
      alliedCommander: 'Vasili Chuikov / Gueorgui Zhúkov', axisCommander: 'Friedrich Paulus',
      alliedStrength: 1143000, axisStrength: 1040000,
      alliedCasualties: 1129000, axisCasualties: 850000, civilianCasualties: 40000,
      description: 'La batalla más sangrienta de la historia. Tras meses de combate urbano casa por casa, la Operación Urano cercó al 6.º Ejército alemán, que capituló en febrero de 1943.',
      strategicImportance: 'Punto de inflexión de toda la guerra en Europa; Alemania nunca recuperó la iniciativa en el Este.',
      participants: [
        { key: 'chuikov', role: 'Comandante del 62.º Ejército' },
        { key: 'zhukov', role: 'Coordinador de la contraofensiva' },
        { key: 'paulus', role: 'Comandante del 6.º Ejército' },
      ],
    },
    {
      key: 'kursk',
      name: 'Batalla de Kursk',
      startDate: d('1943-07-05'), endDate: d('1943-08-23'),
      locationName: 'Kursk, URSS', latitude: 51.7304, longitude: 36.1926,
      theater: Theater.EASTERN_FRONT, victor: Victor.ALLIED,
      alliedCommander: 'Gueorgui Zhúkov / Konstantín Rokossovski', axisCommander: 'Erich von Manstein / Günther von Kluge',
      alliedStrength: 1910000, axisStrength: 780000,
      alliedCasualties: 863000, axisCasualties: 203000, civilianCasualties: 0,
      description: 'La mayor batalla de tanques de la historia. La ofensiva alemana Ciudadela se estrelló contra defensas soviéticas en profundidad, seguida de contraofensivas que liberaron Órel y Járkov.',
      strategicImportance: 'Última gran ofensiva alemana en el Este; desde Kursk el Ejército Rojo avanzó sin pausa hasta Berlín.',
      participants: [
        { key: 'zhukov', role: 'Coordinador de frentes' },
        { key: 'manstein', role: 'Comandante del ataque sur' },
      ],
    },
    {
      key: 'sicily',
      name: 'Invasión de Sicilia (Operación Husky)',
      startDate: d('1943-07-09'), endDate: d('1943-08-17'),
      locationName: 'Sicilia, Italia', latitude: 37.0754, longitude: 14.2401,
      theater: Theater.MEDITERRANEAN, victor: Victor.ALLIED,
      alliedCommander: 'Dwight D. Eisenhower / Harold Alexander', axisCommander: 'Albert Kesselring',
      alliedStrength: 467000, axisStrength: 300000,
      alliedCasualties: 24850, axisCasualties: 165000, civilianCasualties: 5000,
      description: 'El mayor desembarco anfibio de la guerra hasta esa fecha. La caída de Sicilia precipitó la destitución de Mussolini y el armisticio italiano.',
      strategicImportance: 'Abrió el frente mediterráneo y sacó a Italia de la guerra.',
      participants: [
        { key: 'eisenhower', role: 'Comandante supremo' },
        { key: 'patton', role: 'Comandante del 7.º Ejército' },
        { key: 'montgomery', role: 'Comandante del 8.º Ejército' },
      ],
    },
    {
      key: 'montecassino',
      name: 'Batalla de Montecassino',
      startDate: d('1944-01-17'), endDate: d('1944-05-18'),
      locationName: 'Cassino, Italia', latitude: 41.4869, longitude: 13.8135,
      theater: Theater.MEDITERRANEAN, victor: Victor.ALLIED,
      alliedCommander: 'Harold Alexander / Mark Clark', axisCommander: 'Albert Kesselring',
      alliedStrength: 240000, axisStrength: 140000,
      alliedCasualties: 55000, axisCasualties: 20000, civilianCasualties: 2000,
      description: 'Cuatro asaltos aliados contra la Línea Gustav anclada en la abadía de Montecassino. Tropas polacas tomaron finalmente las ruinas, abriendo la ruta hacia Roma.',
      strategicImportance: 'Rompió la Línea Gustav y permitió la liberación de Roma en junio de 1944.',
      participants: [],
    },
    {
      key: 'anzio',
      name: 'Batalla de Anzio',
      startDate: d('1944-01-22'), endDate: d('1944-06-05'),
      locationName: 'Anzio, Italia', latitude: 41.4489, longitude: 12.6289,
      theater: Theater.MEDITERRANEAN, victor: Victor.ALLIED,
      alliedCommander: 'John P. Lucas / Lucian Truscott', axisCommander: 'Albert Kesselring',
      alliedStrength: 150000, axisStrength: 135000,
      alliedCasualties: 43000, axisCasualties: 40000, civilianCasualties: 0,
      description: 'Desembarco a espaldas de la Línea Gustav que quedó embotellado durante meses en la cabeza de playa antes de romper el cerco y enlazar con el avance sobre Roma.',
      strategicImportance: 'Fijó reservas alemanas lejos de Normandía en vísperas del Día D.',
      participants: [],
    },
    {
      key: 'normandy',
      name: 'Desembarco de Normandía (Día D)',
      startDate: d('1944-06-06'), endDate: d('1944-08-30'),
      locationName: 'Normandía, Francia', latitude: 49.3433, longitude: -0.6033,
      theater: Theater.EUROPEAN, victor: Victor.ALLIED,
      alliedCommander: 'Dwight D. Eisenhower / Bernard Montgomery', axisCommander: 'Gerd von Rundstedt / Erwin Rommel',
      alliedStrength: 1332000, axisStrength: 380000,
      alliedCasualties: 226000, axisCasualties: 320000, civilianCasualties: 20000,
      description: 'La mayor operación anfibia de la historia. 156.000 soldados desembarcaron el 6 de junio en cinco playas; la posterior batalla de Normandía destruyó al ejército alemán en el oeste de Francia.',
      strategicImportance: 'Abrió el frente occidental definitivo y condujo a la liberación de Francia.',
      participants: [
        { key: 'eisenhower', role: 'Comandante supremo' },
        { key: 'montgomery', role: 'Comandante de fuerzas terrestres' },
        { key: 'rommel', role: 'Comandante de la defensa costera' },
      ],
    },
    {
      key: 'marketgarden',
      name: 'Operación Market Garden',
      startDate: d('1944-09-17'), endDate: d('1944-09-25'),
      locationName: 'Arnhem, Países Bajos', latitude: 51.9851, longitude: 5.8987,
      theater: Theater.EUROPEAN, victor: Victor.AXIS,
      alliedCommander: 'Bernard Montgomery', axisCommander: 'Walter Model',
      alliedStrength: 41000, axisStrength: 100000,
      alliedCasualties: 17000, axisCasualties: 8000, civilianCasualties: 500,
      description: 'Audaz plan aerotransportado para capturar los puentes del Rin y terminar la guerra en 1944. La 1.ª División Aerotransportada británica fue aniquilada en Arnhem, "un puente demasiado lejos".',
      strategicImportance: 'Su fracaso prolongó la guerra en el oeste hasta 1945.',
      participants: [{ key: 'montgomery', role: 'Planificador de la operación' }],
    },
    {
      key: 'leytegulf',
      name: 'Batalla del Golfo de Leyte',
      startDate: d('1944-10-23'), endDate: d('1944-10-26'),
      locationName: 'Golfo de Leyte, Filipinas', latitude: 10.3599, longitude: 125.2333,
      theater: Theater.PACIFIC, victor: Victor.ALLIED,
      alliedCommander: 'William Halsey / Thomas Kinkaid', axisCommander: 'Takeo Kurita',
      alliedStrength: 143000, axisStrength: 43000,
      alliedCasualties: 3000, axisCasualties: 12500, civilianCasualties: 0,
      description: 'La mayor batalla naval de la historia moderna. La Armada Imperial japonesa fue destruida como fuerza de combate y aparecieron los primeros ataques kamikaze organizados.',
      strategicImportance: 'Aseguró la reconquista de Filipinas y cortó a Japón de sus recursos del sudeste asiático.',
      participants: [{ key: 'macarthur', role: 'Comandante de la invasión de Leyte' }],
    },
    {
      key: 'bulge',
      name: 'Batalla de las Ardenas',
      startDate: d('1944-12-16'), endDate: d('1945-01-25'),
      locationName: 'Bastogne, Bélgica', latitude: 50.0, longitude: 5.7167,
      theater: Theater.EUROPEAN, victor: Victor.ALLIED,
      alliedCommander: 'Dwight D. Eisenhower / Omar Bradley', axisCommander: 'Gerd von Rundstedt / Walter Model',
      alliedStrength: 700000, axisStrength: 450000,
      alliedCasualties: 90000, axisCasualties: 100000, civilianCasualties: 3000,
      description: 'Última gran ofensiva alemana en el oeste, lanzada por sorpresa a través de las Ardenas nevadas. La resistencia en Bastogne y el contraataque de Patton sellaron su fracaso.',
      strategicImportance: 'Consumió las últimas reservas blindadas alemanas, acelerando el final de la guerra.',
      participants: [
        { key: 'eisenhower', role: 'Comandante supremo' },
        { key: 'patton', role: 'Contraataque del 3.er Ejército' },
      ],
    },
    {
      key: 'iwojima',
      name: 'Batalla de Iwo Jima',
      startDate: d('1945-02-19'), endDate: d('1945-03-26'),
      locationName: 'Iwo Jima, Japón', latitude: 24.7514, longitude: 141.2903,
      theater: Theater.PACIFIC, victor: Victor.ALLIED,
      alliedCommander: 'Holland Smith', axisCommander: 'Tadamichi Kuribayashi',
      alliedStrength: 110000, axisStrength: 21000,
      alliedCasualties: 26000, axisCasualties: 20500, civilianCasualties: 0,
      description: 'Los marines conquistaron la isla volcánica fortificada con túneles tras cinco semanas de combate. La foto del izado de la bandera en el monte Suribachi se volvió icónica.',
      strategicImportance: 'Proporcionó base de emergencia a los B-29 que bombardeaban Japón.',
      participants: [{ key: 'nimitz', role: 'Comandante en jefe del Pacífico' }],
    },
    {
      key: 'okinawa',
      name: 'Batalla de Okinawa',
      startDate: d('1945-04-01'), endDate: d('1945-06-22'),
      locationName: 'Okinawa, Japón', latitude: 26.5, longitude: 128.0,
      theater: Theater.PACIFIC, victor: Victor.ALLIED,
      alliedCommander: 'Simon B. Buckner Jr.', axisCommander: 'Mitsuru Ushijima',
      alliedStrength: 250000, axisStrength: 120000,
      alliedCasualties: 50000, axisCasualties: 110000, civilianCasualties: 100000,
      description: 'La batalla más sangrienta del Pacífico: 82 días de combate y oleadas kamikaze contra la flota. La enorme cifra de bajas influyó en la decisión de usar la bomba atómica.',
      strategicImportance: 'Última gran batalla de la guerra; base prevista para la invasión de Japón.',
      participants: [{ key: 'nimitz', role: 'Comandante en jefe del Pacífico' }],
    },
    {
      key: 'berlin',
      name: 'Batalla de Berlín',
      startDate: d('1945-04-16'), endDate: d('1945-05-02'),
      locationName: 'Berlín, Alemania', latitude: 52.52, longitude: 13.405,
      theater: Theater.EASTERN_FRONT, victor: Victor.ALLIED,
      alliedCommander: 'Gueorgui Zhúkov / Iván Kónev', axisCommander: 'Helmuth Weidling',
      alliedStrength: 2500000, axisStrength: 766000,
      alliedCasualties: 361000, axisCasualties: 400000, civilianCasualties: 125000,
      description: 'Asalto final soviético a la capital del Reich. Hitler se suicidó el 30 de abril en su búnker y la guarnición capituló el 2 de mayo ante el general Chuikov.',
      strategicImportance: 'Provocó el colapso final del Tercer Reich y la rendición incondicional de Alemania.',
      participants: [
        { key: 'zhukov', role: 'Comandante del 1.er Frente Bielorruso' },
        { key: 'chuikov', role: 'Comandante del 8.º Ejército de Guardias' },
        { key: 'hitler', role: 'Dirección de la defensa desde el búnker' },
      ],
    },
  ];

  const battles: Record<string, { id: string }> = {};
  for (const { key, participants, ...data } of battlesData) {
    const battle = await prisma.battle.create({ data });
    battles[key] = battle;
    for (const p of participants) {
      await prisma.battleParticipant.create({
        data: { battleId: battle.id, personId: people[p.key].id, role: p.role },
      });
    }
  }

  // ─────────────────────────── CAMPAIGNS ───────────────────────────
  const campaignsData = [
    {
      name: 'Campaña del Norte de África',
      startDate: d('1940-06-10'), endDate: d('1943-05-13'),
      theater: Theater.NORTH_AFRICAN,
      objective: 'Control del norte de África, el canal de Suez y el acceso al petróleo de Oriente Medio.',
      outcome: 'Victoria aliada: rendición de las fuerzas del Eje en Túnez.',
      description: 'Tres años de guerra de vaivén por el desierto libio-egipcio entre el Afrika Korps de Rommel y los ejércitos británicos, decidida en El Alamein y por los desembarcos de la Operación Torch.',
      battles: ['elalamein'],
    },
    {
      name: 'Operación Barbarroja y Frente Oriental',
      startDate: d('1941-06-22'), endDate: d('1945-05-08'),
      theater: Theater.EASTERN_FRONT,
      objective: 'Destrucción de la Unión Soviética y conquista del "espacio vital" en el Este.',
      outcome: 'Derrota total alemana: el Ejército Rojo tomó Berlín.',
      description: 'El mayor frente terrestre de la historia, con más de 30 millones de bajas. De la invasión sorpresa de 1941 a la caída de Berlín, pasando por Moscú, Stalingrado y Kursk.',
      battles: ['moscow', 'leningrad', 'stalingrad', 'kursk', 'berlin'],
    },
    {
      name: 'Guerra del Pacífico',
      startDate: d('1941-12-07'), endDate: d('1945-09-02'),
      theater: Theater.PACIFIC,
      objective: 'Japón: esfera de coprosperidad asiática. Aliados: derrota incondicional de Japón.',
      outcome: 'Rendición de Japón tras Hiroshima, Nagasaki y la entrada soviética.',
      description: 'De Pearl Harbor a la bahía de Tokio: portaaviones, saltos de isla y batallas anfibias cada vez más sangrientas hasta la rendición japonesa.',
      battles: ['pearlharbor', 'coralsea', 'midway', 'guadalcanal', 'leytegulf', 'iwojima', 'okinawa'],
    },
    {
      name: 'Campaña de Italia',
      startDate: d('1943-07-09'), endDate: d('1945-05-02'),
      theater: Theater.MEDITERRANEAN,
      objective: 'Eliminar a Italia de la guerra y fijar fuerzas alemanas lejos de Francia y el Este.',
      outcome: 'Victoria aliada: rendición alemana en Italia el 2 de mayo de 1945.',
      description: 'Desde Sicilia hasta los Alpes: una lenta y costosa campaña de montaña contra sucesivas líneas defensivas alemanas.',
      battles: ['sicily', 'montecassino', 'anzio'],
    },
    {
      name: 'Liberación de Europa Occidental',
      startDate: d('1944-06-06'), endDate: d('1945-05-08'),
      theater: Theater.EUROPEAN,
      objective: 'Abrir el segundo frente, liberar Francia y derrotar a Alemania desde el oeste.',
      outcome: 'Victoria aliada: enlace con los soviéticos en el Elba y rendición alemana.',
      description: 'Del Día D al Elba: la liberación de Francia, el fracaso de Market Garden, la crisis de las Ardenas y el cruce del Rin.',
      battles: ['normandy', 'marketgarden', 'bulge'],
    },
    {
      name: 'Blitzkrieg en Europa Occidental',
      startDate: d('1939-09-01'), endDate: d('1940-10-31'),
      theater: Theater.EUROPEAN,
      objective: 'Alemania: dominio rápido de Europa Central y Occidental.',
      outcome: 'Victoria alemana en el continente; fracaso frente a Gran Bretaña.',
      description: 'La fase inicial de la guerra: Polonia, la "guerra de broma", la caída de Francia y el duelo aéreo sobre Inglaterra.',
      battles: ['poland', 'france', 'dunkirk', 'britain'],
    },
  ];

  for (const { battles: battleKeys, ...data } of campaignsData) {
    const campaign = await prisma.campaign.create({ data });
    for (let i = 0; i < battleKeys.length; i++) {
      await prisma.campaignBattle.create({
        data: { campaignId: campaign.id, battleId: battles[battleKeys[i]].id, battleOrder: i + 1 },
      });
    }
  }

  // ─────────────────────────── EVENTS ───────────────────────────
  const E = EventCategory;
  const eventsData: {
    title: string; eventDate: Date; category: EventCategory;
    significanceLevel: number; region?: string; description: string;
  }[] = [
    { title: 'Pacto Ribbentrop-Mólotov', eventDate: d('1939-08-23'), category: E.POLITICAL, significanceLevel: 5, region: 'Europa', description: 'Alemania y la URSS firman un pacto de no agresión con un protocolo secreto que se reparte Europa Oriental, despejando el camino a la invasión de Polonia.' },
    { title: 'Alemania invade Polonia', eventDate: d('1939-09-01'), category: E.MILITARY, significanceLevel: 5, region: 'Europa', description: 'La Wehrmacht cruza la frontera polaca al amanecer. Comienza la Segunda Guerra Mundial en Europa.' },
    { title: 'Reino Unido y Francia declaran la guerra a Alemania', eventDate: d('1939-09-03'), category: E.POLITICAL, significanceLevel: 5, region: 'Europa', description: 'Cumpliendo sus garantías a Polonia, las potencias occidentales declaran la guerra al Tercer Reich.' },
    { title: 'La URSS invade Polonia oriental', eventDate: d('1939-09-17'), category: E.MILITARY, significanceLevel: 4, region: 'Europa', description: 'El Ejército Rojo ocupa la mitad oriental de Polonia conforme al protocolo secreto del pacto germano-soviético.' },
    { title: 'Alemania invade Dinamarca y Noruega', eventDate: d('1940-04-09'), category: E.MILITARY, significanceLevel: 3, region: 'Escandinavia', description: 'La Operación Weserübung asegura el hierro sueco y las bases navales del Atlántico Norte.' },
    { title: 'Churchill se convierte en primer ministro', eventDate: d('1940-05-10'), category: E.POLITICAL, significanceLevel: 5, region: 'Reino Unido', description: 'El mismo día que Alemania invade Francia y el Benelux, Winston Churchill sustituye a Neville Chamberlain.' },
    { title: 'Italia entra en guerra junto a Alemania', eventDate: d('1940-06-10'), category: E.POLITICAL, significanceLevel: 4, region: 'Mediterráneo', description: 'Mussolini declara la guerra a Francia y Reino Unido buscando repartirse los despojos de la victoria alemana.' },
    { title: 'Francia firma el armisticio', eventDate: d('1940-06-22'), category: E.POLITICAL, significanceLevel: 5, region: 'Europa', description: 'Francia capitula en el mismo vagón de tren de Compiègne donde Alemania firmó el armisticio de 1918. Nace la Francia de Vichy.' },
    { title: 'Llamamiento del 18 de junio de De Gaulle', eventDate: d('1940-06-18'), category: E.POLITICAL, significanceLevel: 4, region: 'Europa', description: 'Desde la BBC en Londres, De Gaulle llama a los franceses a continuar la lucha: nace la Francia Libre.' },
    { title: 'Pacto Tripartito', eventDate: d('1940-09-27'), category: E.POLITICAL, significanceLevel: 4, region: 'Global', description: 'Alemania, Italia y Japón formalizan el Eje Roma-Berlín-Tokio con un tratado de asistencia mutua.' },
    { title: 'Ley de Préstamo y Arriendo', eventDate: d('1941-03-11'), category: E.ECONOMIC, significanceLevel: 5, region: 'EE.UU.', description: 'EE.UU. se convierte en el "arsenal de la democracia": suministrará más de 50.000 millones de dólares en material a los Aliados.' },
    { title: 'Alemania invade la URSS (Operación Barbarroja)', eventDate: d('1941-06-22'), category: E.MILITARY, significanceLevel: 5, region: 'Frente Oriental', description: 'Más de tres millones de soldados del Eje cruzan la frontera soviética en la mayor invasión de la historia.' },
    { title: 'Carta del Atlántico', eventDate: d('1941-08-14'), category: E.POLITICAL, significanceLevel: 4, region: 'Global', description: 'Roosevelt y Churchill proclaman los principios del mundo de posguerra, germen de las Naciones Unidas.' },
    { title: 'Ataque a Pearl Harbor', eventDate: d('1941-12-07'), category: E.MILITARY, significanceLevel: 5, region: 'Pacífico', description: 'Japón ataca por sorpresa la flota estadounidense en Hawái. "Una fecha que vivirá en la infamia".' },
    { title: 'EE.UU. declara la guerra a Japón', eventDate: d('1941-12-08'), category: E.POLITICAL, significanceLevel: 5, region: 'Global', description: 'El Congreso declara la guerra con un solo voto en contra. Tres días después, Alemania e Italia declaran la guerra a EE.UU.' },
    { title: 'Caída de Singapur', eventDate: d('1942-02-15'), category: E.MILITARY, significanceLevel: 4, region: 'Pacífico', description: 'La mayor capitulación de la historia británica: 80.000 soldados se rinden a un ejército japonés inferior en número.' },
    { title: 'Conferencia de Wannsee', eventDate: d('1942-01-20'), category: E.POLITICAL, significanceLevel: 5, region: 'Europa', description: 'Altos cargos nazis coordinan la "Solución Final": la deportación y exterminio sistemático de los judíos de Europa.' },
    { title: 'Bombardeo de Tokio (Doolittle Raid)', eventDate: d('1942-04-18'), category: E.MILITARY, significanceLevel: 3, region: 'Pacífico', description: 'Dieciséis B-25 lanzados desde el portaaviones Hornet bombardean Japón: daño simbólico, impacto psicológico enorme.' },
    { title: 'Operación Torch: desembarcos en el norte de África', eventDate: d('1942-11-08'), category: E.MILITARY, significanceLevel: 4, region: 'Norte de África', description: 'Tropas angloamericanas desembarcan en Marruecos y Argelia, atrapando al Eje entre dos frentes en África.' },
    { title: 'Conferencia de Casablanca', eventDate: d('1943-01-14'), category: E.POLITICAL, significanceLevel: 4, region: 'Global', description: 'Roosevelt y Churchill acuerdan exigir la rendición incondicional del Eje y planifican la invasión de Sicilia.' },
    { title: 'Rendición alemana en Stalingrado', eventDate: d('1943-02-02'), category: E.MILITARY, significanceLevel: 5, region: 'Frente Oriental', description: 'Los restos del 6.º Ejército capitulan. Alemania pierde 300.000 hombres y el aura de invencibilidad.' },
    { title: 'Levantamiento del gueto de Varsovia', eventDate: d('1943-04-19'), category: E.MILITARY, significanceLevel: 4, region: 'Europa', description: 'Los judíos del gueto se alzan en armas contra la deportación. Resisten casi un mes antes de la destrucción total del gueto.' },
    { title: 'Rendición del Eje en Túnez', eventDate: d('1943-05-13'), category: E.MILITARY, significanceLevel: 4, region: 'Norte de África', description: 'Más de 230.000 soldados alemanes e italianos se rinden: África queda limpia de fuerzas del Eje.' },
    { title: 'Caída de Mussolini', eventDate: d('1943-07-25'), category: E.POLITICAL, significanceLevel: 4, region: 'Mediterráneo', description: 'El Gran Consejo Fascista destituye a Mussolini tras la invasión de Sicilia; es arrestado por orden del rey.' },
    { title: 'Armisticio de Italia', eventDate: d('1943-09-08'), category: E.POLITICAL, significanceLevel: 4, region: 'Mediterráneo', description: 'Italia se rinde a los Aliados; Alemania ocupa el norte y centro del país y libera a Mussolini.' },
    { title: 'Conferencia de Teherán', eventDate: d('1943-11-28'), category: E.POLITICAL, significanceLevel: 4, region: 'Global', description: 'Primera reunión de los "Tres Grandes": Stalin obtiene el compromiso del segundo frente en Francia para 1944.' },
    { title: 'Día D: desembarco de Normandía', eventDate: d('1944-06-06'), category: E.MILITARY, significanceLevel: 5, region: 'Europa', description: 'La mayor operación anfibia de la historia abre el segundo frente en Europa Occidental.' },
    { title: 'Operación Bagratión', eventDate: d('1944-06-22'), category: E.MILITARY, significanceLevel: 5, region: 'Frente Oriental', description: 'La ofensiva soviética de verano destruye el Grupo de Ejércitos Centro: la mayor derrota de la historia militar alemana.' },
    { title: 'Atentado del 20 de julio contra Hitler', eventDate: d('1944-07-20'), category: E.POLITICAL, significanceLevel: 4, region: 'Europa', description: 'La bomba de Stauffenberg falla por poco. La purga posterior ejecuta a unos 5.000 opositores, incluido (indirectamente) Rommel.' },
    { title: 'Liberación de París', eventDate: d('1944-08-25'), category: E.MILITARY, significanceLevel: 4, region: 'Europa', description: 'La 2.ª División Blindada de Leclerc y la resistencia liberan la capital francesa tras cuatro años de ocupación.' },
    { title: 'Acuerdos de Bretton Woods', eventDate: d('1944-07-22'), category: E.ECONOMIC, significanceLevel: 4, region: 'Global', description: '44 naciones diseñan el orden económico de posguerra: nacen el FMI y el Banco Mundial y el dólar ancla el sistema monetario.' },
    { title: 'Conferencia de Yalta', eventDate: d('1945-02-04'), category: E.POLITICAL, significanceLevel: 5, region: 'Global', description: 'Los Tres Grandes se reparten las zonas de ocupación de Alemania y sientan las bases del orden (y la división) de posguerra.' },
    { title: 'Bombardeo de Dresde', eventDate: d('1945-02-13'), category: E.MILITARY, significanceLevel: 3, region: 'Europa', description: 'La tormenta de fuego provocada por los bombardeos aliados destruye la ciudad y mata a unas 25.000 personas.' },
    { title: 'Muerte de Roosevelt', eventDate: d('1945-04-12'), category: E.POLITICAL, significanceLevel: 4, region: 'EE.UU.', description: 'El presidente muere de una hemorragia cerebral semanas antes de la victoria. Harry Truman asume la presidencia.' },
    { title: 'Suicidio de Hitler', eventDate: d('1945-04-30'), category: E.POLITICAL, significanceLevel: 5, region: 'Europa', description: 'Con el Ejército Rojo a metros de la Cancillería, Hitler se suicida en su búnker junto a Eva Braun.' },
    { title: 'Día de la Victoria en Europa (V-E Day)', eventDate: d('1945-05-08'), category: E.MILITARY, significanceLevel: 5, region: 'Europa', description: 'Alemania firma la rendición incondicional. Termina la guerra en Europa tras casi seis años.' },
    { title: 'Prueba Trinity: primera bomba atómica', eventDate: d('1945-07-16'), category: E.MILITARY, significanceLevel: 5, region: 'EE.UU.', description: 'El Proyecto Manhattan detona con éxito la primera arma nuclear de la historia en el desierto de Nuevo México.' },
    { title: 'Conferencia de Potsdam', eventDate: d('1945-07-17'), category: E.POLITICAL, significanceLevel: 4, region: 'Global', description: 'Truman, Stalin y Attlee definen la administración de la Alemania ocupada y lanzan el ultimátum a Japón.' },
    { title: 'Bomba atómica sobre Hiroshima', eventDate: d('1945-08-06'), category: E.MILITARY, significanceLevel: 5, region: 'Pacífico', description: 'El B-29 Enola Gay lanza "Little Boy": unas 80.000 personas mueren instantáneamente y decenas de miles más por la radiación.' },
    { title: 'La URSS declara la guerra a Japón; bomba sobre Nagasaki', eventDate: d('1945-08-09'), category: E.MILITARY, significanceLevel: 5, region: 'Pacífico', description: 'El Ejército Rojo invade Manchuria y "Fat Man" destruye Nagasaki: el doble golpe que precipita la rendición japonesa.' },
    { title: 'Rendición de Japón (V-J Day)', eventDate: d('1945-09-02'), category: E.MILITARY, significanceLevel: 5, region: 'Pacífico', description: 'Japón firma la rendición a bordo del USS Missouri en la bahía de Tokio. Termina la Segunda Guerra Mundial.' },
    { title: 'Racionamiento en el Reino Unido', eventDate: d('1940-01-08'), category: E.ECONOMIC, significanceLevel: 2, region: 'Reino Unido', description: 'Comienza el racionamiento de alimentos básicos, que llegaría a cubrir casi todos los productos y duraría hasta 1954.' },
    { title: 'Estreno de "Casablanca"', eventDate: d('1942-11-26'), category: E.CULTURAL, significanceLevel: 2, region: 'EE.UU.', description: 'El clásico de Michael Curtiz, ambientado en el Marruecos de Vichy, se estrena semanas después de la Operación Torch.' },
    { title: 'Emisión del discurso "sangre, sudor y lágrimas"', eventDate: d('1940-05-13'), category: E.CULTURAL, significanceLevel: 3, region: 'Reino Unido', description: 'Churchill pronuncia su primer gran discurso como primer ministro ante los Comunes, definiendo el tono de la resistencia británica.' },
    { title: 'Las mujeres se incorporan masivamente a la industria bélica', eventDate: d('1942-01-01'), category: E.CULTURAL, significanceLevel: 3, region: 'EE.UU.', description: 'El icono de "Rosie the Riveter" simboliza a los millones de mujeres que sostuvieron la producción de guerra estadounidense.' },
    { title: 'Diario de Ana Frank: la familia se esconde', eventDate: d('1942-07-06'), category: E.CULTURAL, significanceLevel: 3, region: 'Europa', description: 'La familia Frank se oculta en el anexo secreto de Ámsterdam. El diario de Ana se convertirá en el testimonio más leído del Holocausto.' },
  ];

  await prisma.event.createMany({
    data: eventsData.map((e) => ({ ...e, significanceLevel: e.significanceLevel })),
  });

  const counts = {
    people: await prisma.person.count(),
    battles: await prisma.battle.count(),
    campaigns: await prisma.campaign.count(),
    events: await prisma.event.count(),
    participants: await prisma.battleParticipant.count(),
  };
  console.log('Seed completado:', counts);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
